name: Nuclei Vulnerability Scan

on:
  schedule:
    - cron: "0 11 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  nuclei:
    name: Nuclei
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/nuclei.yml@7ed8c494c4d1ceef7dc78b18c4c8c72166073440  # v0.2.3
    with:
      urls_file: .github/workflows/nuclei/sb.txt
