name: Nuclei Vulnerability Scan

on:
  schedule:
    - cron: "0 11 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  nuclei:
    name: Nuclei
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/nuclei.yml@cd7f9e2c86fe5bbafd21b8f12cc0e6cbe504f0f7  # v0.2.8
    with:
      urls_file: .github/workflows/nuclei/sb.txt
